--------------------------------------------------------------------
----- CREATE IDW_STAGED_USERS_VIEW -----
--------------------------------------------------------------------

CREATE OR ALTER VIEW [IDW].[IDW_STAGED_USERS_VIEW]
AS
    WITH EMPLOYEES AS (
        SELECT E.IDW_GUID, E.IDW_PRIMARY_KEY, CASE WHEN M.UID IS NULL THEN (SELECT [IDW].[GENERATE_UID]()) ELSE M.UID END AS UID, 'EMPLOYEE' AS PERSON_TYPE, E.EMPLOYEE_ID, NULL AS CONTRACTOR_ID, E.FIRST_NAME, E.MIDDLE_NAME, E.LAST_NAME, E.HIRE_DATE, E.TERMINATION_DATE, E.STATUS, E.EMPLOYEE_TYPE, E.LOCATION_NUMBER, E.LOCATION_DESCRIPTION, E.JOB_TITLE, E.JOB_TITLE_DESCRIPTION, E.COST_CENTER, E.MANAGER_EMPLOYEE_ID, E.PERSONAL_EMAIL, E.PHONE_NUMBER, (SELECT [IDW].[GENERATE_EMAIL] (E.FIRST_NAME, E.MIDDLE_NAME, E.LAST_NAME)) AS WORK_EMAIL
        FROM IDW.HR_EMPLOYEE_STG AS E
        LEFT JOIN IDW.IDW_WKR_MAIN AS M ON M.IDW_GUID = E.IDW_GUID
    ),
    CONTRACTORS AS (
        SELECT C.IDW_GUID, C.IDW_PRIMARY_KEY, CASE WHEN M.UID IS NULL THEN (SELECT [IDW].[GENERATE_UID]()) ELSE M.UID END AS UID, 'CONTRACTOR' AS PERSON_TYPE, NULL AS EMPLOYEE_ID, C.CONTRACTOR_ID, C.FIRST_NAME, C.MIDDLE_NAME, C.LAST_NAME, C.HIRE_DATE, C.TERMINATION_DATE, C.STATUS, NULL AS EMPLOYEE_TYPE, C.LOCATION_NUMBER, C.LOCATION_DESCRIPTION, C.JOB_TITLE, C.JOB_TITLE_DESCRIPTION, C.COST_CENTER, C.MANAGER_EMPLOYEE_ID, C.PERSONAL_EMAIL, C.PHONE_NUMBER, (SELECT [IDW].[GENERATE_EMAIL] (C.FIRST_NAME, C.MIDDLE_NAME, C.LAST_NAME)) AS WORK_EMAIL
        FROM IDW.HR_CONTRACTOR_STG AS C
        LEFT JOIN IDW.IDW_WKR_MAIN AS M ON M.IDW_GUID = C.IDW_GUID
    )

    SELECT IDW_GUID, IDW_PRIMARY_KEY, UID, PERSON_TYPE, EMPLOYEE_ID, CONTRACTOR_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, HIRE_DATE, TERMINATION_DATE, STATUS, EMPLOYEE_TYPE, LOCATION_NUMBER, LOCATION_DESCRIPTION, JOB_TITLE, JOB_TITLE_DESCRIPTION, COST_CENTER, MANAGER_EMPLOYEE_ID, PERSONAL_EMAIL, PHONE_NUMBER, WORK_EMAIL
    FROM EMPLOYEES
    UNION ALL
    SELECT IDW_GUID, IDW_PRIMARY_KEY, UID, PERSON_TYPE, EMPLOYEE_ID, CONTRACTOR_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, HIRE_DATE, TERMINATION_DATE, STATUS, EMPLOYEE_TYPE, LOCATION_NUMBER, LOCATION_DESCRIPTION, JOB_TITLE, JOB_TITLE_DESCRIPTION, COST_CENTER, MANAGER_EMPLOYEE_ID, PERSONAL_EMAIL, PHONE_NUMBER, WORK_EMAIL
    FROM CONTRACTORS
GO

