--------------------------------------------------------------------
----- CREATE HR_DATA_STG -----
--------------------------------------------------------------------

CREATE TABLE [IDW].[HR_DATA_STG] (
    EMPLOYEE_ID VARCHAR(255) NULL,
    FIRST_NAME VARCHAR(255) NULL,
    MIDDLE_NAME VARCHAR(255) NULL,
    LAST_NAME VARCHAR(255) NULL,
    HIRE_DATE VARCHAR(255) NULL,
    STATUS VARCHAR(255) NULL,
    EMPLOYEE_TYPE VARCHAR(255) NULL,
    LOCATION_NUMBER VARCHAR(255) NULL,
    LOCACTION_DESCRIPTION VARCHAR(255) NULL,
    JOB_TITLE VARCHAR(255) NULL,
    JOB_TITLE_DESCRIPTION VARCHAR(255) NULL,
    COST_CENTER VARCHAR(255) NULL,
    MANAGER_EMPLOYEE_ID VARCHAR(255) NULL,
    PERSONAL_EMAIL VARCHAR(255) NULL,
    PHONE_NUMBER VARCHAR(255) NULL
)
GO

